#!/usr/bin/env python3
"""Standalone GUI: collect elevation-map reconstruction data, then train."""
import os
import sys
import traceback
import threading
from datetime import datetime

import numpy as np
import onnxruntime as ort
import yaml
from PyQt5.QtCore import QThread, pyqtSignal, Qt
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import (QApplication, QComboBox, QFileDialog, QFormLayout, QGroupBox, QHBoxLayout,
                             QLabel, QLineEdit, QMainWindow, QMessageBox, QProgressBar, QPushButton, QDialog,
                             QTextEdit, QVBoxLayout, QWidget)

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)
from core.elevation_reconstruction import save_dataset, train
from envs.build import build_env

COLLECTION_TERRAINS = [
    "beam_easy", "stairs_up_easy", "stairs_up_normal", "stairs_up_hard",
    "rocky_easy", "rocky_hard", "slope_easy", "slope_hard",
]


def make_config(env_id, terrain, width, height, resolution, samples, render=False):
    with open(os.path.join(ROOT, "config", "env_table.yaml"), encoding="utf-8") as f:
        table = yaml.safe_load(f)
    with open(os.path.join(ROOT, "config", "random_table.yaml"), encoding="utf-8") as f:
        random_table = yaml.safe_load(f)["random_table"]
    spec = table[env_id]
    # The ray grid includes both endpoints, matching Isaac Lab's grid pattern.
    res_x, res_y = max(1, round(width / resolution) + 1), max(1, round(height / resolution) + 1)
    elevation_observations = {"height_map", "masked_height_map", "camera_height_map"}
    stacked = [name for name in spec.get("stacked_obs_order", []) if name not in elevation_observations]
    # The elevation map is generated by the environment only for collection.
    # Remove even pre-existing map terms from the policy state vector.
    non_stacked = [name for name in spec.get("non_stacked_obs_order", []) if name not in elevation_observations]
    scales = spec.get("obs_scales", {})
    settings = {"stacked_obs_order": stacked, "non_stacked_obs_order": non_stacked,
                "stack_size": int(spec.get("stack_size", 1)),
                "command_dim": int(spec.get("command", {}).get("command_dim", 3)),
                "command_scales": spec.get("command_scales", {"0": 1., "1": 1., "2": 1.}),
                "height_map": {"size_x": width, "size_y": height, "res_x": res_x, "res_y": res_y}}
    for name in set(stacked + non_stacked):
        if name == "height_map":
            settings[name].update({"freq": 50, "scale": float(scales.get(name, 1.0))})
        else:
            settings[name] = {"freq": 50, "scale": float(scales.get(name, 1.0))}
    return {
        # Compact beam field: the robot reaches many obstacles within a short rollout.
        "env": {"id": env_id, "terrain": terrain, "beam": {"beam_start_x": 0.8, "beam_spacing": 0.45, "beam_height": 0.15, "beam_count": 24}, "max_duration": max(5., samples / 50.),
                "position_command": False, "render": render, "render_mode": "human", "quiet": True},
        "settings": settings, "observation": settings, "policy": {"policy_type": "MLP"},
        "hardware": spec["hardware"], "action_scales": spec.get("action_scales", []),
        "initial_positions": spec.get("initial_pose", {}), "joint_offsets": spec.get("initial_pose", {}),
        "actuator": {}, "random": {"precision": "medium", "sensor_noise": "none", "init_noise": 0.,
            "sliding_friction": 1., "torsional_friction": .5, "rolling_friction": .01,
            "friction_loss": 0., "action_delay_prob": 0., "mass_noise": 0., "load": 0.},
        "random_table": random_table,
    }, (res_y, res_x)


class Job(QThread):
    message = pyqtSignal(str); progress = pyqtSignal(int); failed = pyqtSignal(str); complete = pyqtSignal(str)
    def __init__(self, values): super().__init__(); self.values = values
    def run(self):
        env = None
        try:
            v = self.values; terrains = list(COLLECTION_TERRAINS)
            session = ort.InferenceSession(v["policy"], providers=["CPUExecutionProvider"])
            input_info = session.get_inputs()[0]
            maps=[]; gravities=[]; targets=[]; rng=np.random.default_rng(42); terrain_summary=[]
            base_count, remainder = divmod(v["samples"], len(terrains)); shape = None; collected = 0
            for terrain_index, terrain in enumerate(terrains):
                count = base_count + (1 if terrain_index < remainder else 0)
                config, current_shape = make_config(v["env"], terrain, v["width"], v["height"], v["resolution"], count)
                shape = shape or current_shape
                self.message.emit(f"Terrain {terrain_index + 1}/{len(terrains)}: {terrain} — collecting {count:,} samples (obstacle-priority)")
                env = build_env(config); state, _ = env.reset()
                if tuple(input_info.shape[-1:]) != (state.size,):
                    raise RuntimeError(f"Policy expects {input_info.shape[-1]} observations but '{v['env']}' produces {state.size}. Choose a matching policy/map specification.")
                command=np.zeros(config["settings"]["command_dim"], dtype=np.float32)
                command[0]=0.6  # Traverse the compact field instead of standing at its start.
                env.receive_user_command(command)
                accepted = flat_accepted = obstacle_accepted = attempts = 0
                flat_budget=max(1, int(np.ceil(count * 0.15))); max_attempts=max(200, count * 10)
                while accepted < count:
                    action = session.run(None, {input_info.name: state[None].astype(np.float32)})[0][0]
                    state, terminated, truncated, _ = env.step(action)
                    obs = env.get_last_obs(); target = np.asarray(obs["height_map"], dtype=np.float32).reshape(-1)
                    gravity = np.asarray(obs["projected_gravity"], dtype=np.float32).reshape(3)
                    attempts += 1
                    # A 3 cm height range marks a locally visible obstacle/edge.
                    obstacle_frame = float(np.ptp(target)) >= 0.03
                    accept = obstacle_frame or flat_accepted < flat_budget or attempts >= max_attempts
                    if accept:
                        maps.append(target + rng.normal(0., v["map_noise"], target.shape)); gravities.append(gravity + rng.normal(0., v["gravity_noise"], 3)); targets.append(target)
                        accepted += 1; collected += 1
                        if obstacle_frame: obstacle_accepted += 1
                        else: flat_accepted += 1
                    if accept and collected % 100 == 0: self.message.emit(f"Collecting elevation sample {collected:,} / {v['samples']:,}")
                    self.progress.emit(int(collected * 55 / v["samples"]))
                    if terminated or truncated: state, _ = env.reset(); env.receive_user_command(command)
                    if attempts == max_attempts and accepted < count:
                        self.message.emit(f"{terrain}: obstacle quota unavailable after {attempts:,} rollout steps; filling remaining frames.")
                        flat_budget = count
                terrain_summary.append({"terrain": terrain, "accepted": accepted, "obstacle_frames": obstacle_accepted, "attempts": attempts})
                self.message.emit(f"{terrain}: {obstacle_accepted:,}/{accepted:,} accepted maps contain >=3 cm local relief ({attempts:,} rollout steps)")
                env.close(); env = None
            output = os.path.join(ROOT, "envs", v["env"], "dataset")
            dataset = save_dataset(output, maps, gravities, targets, {"env": v["env"], "terrains": terrains, "map_shape": shape, "map_noise": v["map_noise"], "gravity_noise": v["gravity_noise"], "policy": v["policy"], "forward_command": .6, "obstacle_priority": {"relief_threshold_m": .03, "flat_frame_budget_ratio": .15, "terrain_summary": terrain_summary}, "compact_beam_settings": {"beam_start_x": .8, "beam_spacing": .45, "beam_height": .15, "beam_count": 24}})
            self.message.emit(f"dataset saved: {dataset}")
            self.progress.emit(60)
            def train_log(text):
                self.message.emit(text)
            result = train(dataset, os.path.join(ROOT, "envs", v["env"], "weights"), v["epochs"], log=train_log)
            self.progress.emit(100)
            self.complete.emit(f"Done. {result['samples']} samples\nONNX: {result['onnx']}")
        except Exception: self.failed.emit(traceback.format_exc())
        finally:
            if env is not None: env.close()


def map_pixmap(values, lo, hi):
    values = np.asarray(values, dtype=np.float32)
    if hi - lo < 1e-6: hi = lo + 1e-6
    normalized = np.clip((values - lo) / (hi - lo), 0., 1.)
    # Compact blue -> cyan -> yellow heatmap without a matplotlib dependency.
    rgb = np.stack((np.clip(2 * normalized - .25, 0, 1), np.clip(1.5 - np.abs(2 * normalized - 1), 0, 1), np.clip(1.25 - 2 * normalized, 0, 1)), axis=-1)
    image = QImage((rgb * 255).astype(np.uint8).data, rgb.shape[1], rgb.shape[0], rgb.shape[1] * 3, QImage.Format_RGB888).copy()
    return QPixmap.fromImage(image).scaled(360, 220, Qt.KeepAspectRatio, Qt.FastTransformation)


class PreviewDialog(QDialog):
    command_changed = pyqtSignal(int, float)
    reset_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent); self.setWindowTitle("Elevation map — GT vs reconstruction"); self.resize(780, 360); self.setFocusPolicy(Qt.StrongFocus); self._held_keys=set()
        layout = QVBoxLayout(self); info=QLabel("Live compact beam_easy rollout. Keep this window focused: W/S forward/back, A/D yaw, Z/X lateral; R resets. The separate MuJoCo window shows the same robot and obstacles."); info.setWordWrap(True); info.setStyleSheet("color:#475569;"); layout.addWidget(info)
        row=QHBoxLayout(); layout.addLayout(row); self.gt=QLabel("Waiting for GT elevation map"); self.pred=QLabel("Waiting for ONNX inference");
        self.gt.setAlignment(Qt.AlignCenter); self.pred.setAlignment(Qt.AlignCenter); row.addWidget(self.gt); row.addWidget(self.pred)
        self.metrics=QLabel("RMSE: —"); self.metrics.setAlignment(Qt.AlignCenter); layout.addWidget(self.metrics)
    def update_maps(self, gt, prediction):
        lo, hi = np.percentile(np.concatenate((np.ravel(gt), np.ravel(prediction))), [2, 98])
        self.gt.setPixmap(map_pixmap(gt, lo, hi)); self.pred.setPixmap(map_pixmap(prediction, lo, hi))
        rmse=float(np.sqrt(np.mean((np.asarray(gt)-np.asarray(prediction))**2)))
        self.metrics.setText(f"GT elevation map                                      ONNX reconstruction\nRMSE: {rmse:.4f} m")
    def keyPressEvent(self, event):
        if event.isAutoRepeat(): return
        key=event.key()
        if key == Qt.Key_R: self.reset_requested.emit(); return
        mapping={Qt.Key_W:(0,1.), Qt.Key_S:(0,-1.), Qt.Key_A:(2,1.), Qt.Key_D:(2,-1.), Qt.Key_Z:(1,-1.), Qt.Key_X:(1,1.)}
        if key in mapping:
            self._held_keys.add(key); self._send_command(mapping); return
        super().keyPressEvent(event)
    def keyReleaseEvent(self, event):
        if event.isAutoRepeat(): return
        mapping={Qt.Key_W:(0,1.), Qt.Key_S:(0,-1.), Qt.Key_A:(2,1.), Qt.Key_D:(2,-1.), Qt.Key_Z:(1,-1.), Qt.Key_X:(1,1.)}
        if event.key() in mapping:
            self._held_keys.discard(event.key()); self._send_command(mapping); return
        super().keyReleaseEvent(event)
    def _send_command(self, mapping):
        for index in (0, 1, 2):
            value=sum(direction for key,(command_index,direction) in mapping.items() if key in self._held_keys and command_index == index)
            self.command_changed.emit(index, value)


class PreviewJob(QThread):
    frame = pyqtSignal(object, object); message = pyqtSignal(str); failed = pyqtSignal(str)
    def __init__(self, values):
        super().__init__(); self.values=values; self.stop_requested=False; self.reset_requested=False
        self.command=np.zeros(3,dtype=np.float32); self.command_lock=threading.Lock()
    def stop(self): self.stop_requested=True
    def set_command(self, index, value):
        with self.command_lock:
            if index < self.command.size: self.command[index]=value
    def request_reset(self): self.reset_requested=True
    def run(self):
        env=None
        try:
            v=self.values; config,_=make_config(v["env"], "beam_easy", v["width"], v["height"], v["resolution"], 360000, render=True)
            policy=ort.InferenceSession(v["policy"],providers=["CPUExecutionProvider"])
            restorer_path=os.path.join(ROOT,"envs",v["env"],"weights","elevation_reconstruction","latest","elevation_restorer.onnx")
            if not os.path.isfile(restorer_path): raise RuntimeError(f"Train the elevation model first: {restorer_path}")
            restorer=ort.InferenceSession(restorer_path,providers=["CPUExecutionProvider"])
            env=build_env(config); state,_=env.reset(); env.render(); policy_input=policy.get_inputs()[0]
            if policy_input.shape[-1] != state.size: raise RuntimeError(f"Policy expects {policy_input.shape[-1]} observations but preview environment produces {state.size}.")
            map_size=config["settings"]["height_map"]["res_x"] * config["settings"]["height_map"]["res_y"]
            if restorer.get_inputs()[0].shape[-1] != map_size:
                raise RuntimeError(f"Restoration ONNX expects {restorer.get_inputs()[0].shape[-1]} map values but this preview produces {map_size}. Use the same map size and resolution used for training.")
            env.receive_user_command(np.zeros(config["settings"]["command_dim"],dtype=np.float32)); rng=np.random.default_rng(123); step=0
            self.message.emit("Interactive preview started: focus the map window, then use W/S, A/D, Z/X. Press R to reset; close it to stop.")
            while not self.stop_requested:
                if self.stop_requested: break
                if self.reset_requested:
                    state,_=env.reset(); self.reset_requested=False
                with self.command_lock: command=self.command.copy()
                env.receive_user_command(command)
                action=policy.run(None,{policy_input.name:state[None].astype(np.float32)})[0][0]
                # Same render-before-step order as the normal launch tester.
                env.render(); state,terminated,truncated,_=env.step(action)
                obs=env.get_last_obs(); gt=np.asarray(obs["height_map"],dtype=np.float32).reshape(config["settings"]["height_map"]["res_y"],config["settings"]["height_map"]["res_x"])
                gravity=np.asarray(obs["projected_gravity"],dtype=np.float32).reshape(1,3)
                noisy=(gt.reshape(1,-1)+rng.normal(0.,v["map_noise"],(1,gt.size))).astype(np.float32)
                gravity=(gravity+rng.normal(0.,v["gravity_noise"],(1,3))).astype(np.float32)
                prediction=restorer.run(None,{"noisy_elevation":noisy})[0].reshape(gt.shape)
                if step % 10 == 0: self.frame.emit(gt,prediction)
                if terminated or truncated: state,_=env.reset(); env.receive_user_command(np.zeros(config["settings"]["command_dim"],dtype=np.float32))
                step += 1
        except Exception: self.failed.emit(traceback.format_exc())
        finally:
            if env is not None: env.close()


class Window(QMainWindow):
    def __init__(self):
        super().__init__(); self.setWindowTitle("Elevation Reconstruction Training"); self.resize(650, 520)
        with open(os.path.join(ROOT, "config", "env_table.yaml"), encoding="utf-8") as f: self.envs = list(yaml.safe_load(f))
        root = QWidget(); self.setCentralWidget(root); layout = QVBoxLayout(root); layout.setSpacing(12)
        self.setStyleSheet("QMainWindow { background: #f8fafc; } QGroupBox { font-weight: 600; border: 1px solid #cbd5e1; border-radius: 8px; margin-top: 8px; padding: 10px; background: white; } QGroupBox::title { subcontrol-origin: margin; left: 12px; padding: 0 4px; } QPushButton { background: #2563eb; color: white; border: 0; border-radius: 6px; padding: 9px 14px; font-weight: 600; } QPushButton:disabled { background: #94a3b8; } QLineEdit, QComboBox { padding: 6px; border: 1px solid #cbd5e1; border-radius: 5px; background: white; } QTextEdit { border: 1px solid #cbd5e1; border-radius: 6px; background: #0f172a; color: #dbeafe; font-family: monospace; }")
        intro=QLabel("Collect clean elevation maps while a selected policy drives the robot, then train a separate denoising/restoration model. The elevation map is never added to the policy input."); intro.setWordWrap(True); intro.setStyleSheet("color:#475569;"); layout.addWidget(intro)
        config_group=QGroupBox("Collection setup"); layout.addWidget(config_group); form = QFormLayout(config_group)
        self.env = QComboBox(); self.env.addItems(self.envs)
        self.policy = QLineEdit(); pick = QPushButton("Select ONNX"); pick.clicked.connect(self.pick_policy); row=QHBoxLayout(); row.addWidget(self.policy); row.addWidget(pick)
        self.width=QLineEdit("1.7"); self.height=QLineEdit("0.7"); self.resolution=QLineEdit("0.1"); self.map_noise=QLineEdit("0.1"); self.gravity_noise=QLineEdit("0.0"); self.samples=QLineEdit("200000"); self.epochs=QLineEdit("80")
        terrain_note=QLabel("Automatically cycles all non-flat terrains. A forward command traverses compact obstacles; locally flat frames are capped at 15% per terrain."); terrain_note.setWordWrap(True); terrain_note.setStyleSheet("color:#64748b;")
        for label, widget in [("Robot",self.env),("Collection terrains",terrain_note),("Policy",row),("Map width (m)",self.width),("Map height (m)",self.height),("Resolution (m)",self.resolution),("Elevation noise σ",self.map_noise),("Projected gravity noise σ",self.gravity_noise),("Collection samples",self.samples),("Epochs",self.epochs)]: form.addRow(label,widget)
        self.shape_hint=QLabel(); self.shape_hint.setStyleSheet("color:#64748b;"); form.addRow("Generated map",self.shape_hint)
        for field in (self.width,self.height,self.resolution): field.textChanged.connect(self.update_shape_hint)
        self.update_shape_hint()
        buttons=QHBoxLayout(); self.start=QPushButton("Collect dataset and train restoration model"); self.start.clicked.connect(self.start_job); self.preview_button=QPushButton("Show robot + GT vs inference"); self.preview_button.clicked.connect(self.show_preview); buttons.addWidget(self.start); buttons.addWidget(self.preview_button); layout.addLayout(buttons)
        self.progress=QProgressBar(); self.progress.setValue(0); self.progress.setFormat("Ready — 0%"); layout.addWidget(self.progress)
        log_group=QGroupBox("Run log"); log_layout=QVBoxLayout(log_group); self.log=QTextEdit(); self.log.setReadOnly(True); log_layout.addWidget(self.log); layout.addWidget(log_group,1)
    def update_shape_hint(self):
        try:
            shape=(round(float(self.height.text())/float(self.resolution.text()))+1, round(float(self.width.text())/float(self.resolution.text()))+1)
            self.shape_hint.setText(f"{shape[1]} × {shape[0]} cells ({shape[0]*shape[1]:,} values); collection only, not policy input")
        except Exception: self.shape_hint.setText("Enter valid width, height, and resolution")
    def append_log(self, text):
        self.log.append(f"[{datetime.now().strftime('%H:%M:%S')}] {text}")
    def pick_policy(self):
        path,_=QFileDialog.getOpenFileName(self,"Select policy",ROOT,"ONNX (*.onnx)"); self.policy.setText(path)
    def start_job(self):
        if not os.path.isfile(self.policy.text()): QMessageBox.warning(self,"Policy", "Select a valid ONNX policy."); return
        try: v={"env":self.env.currentText(),"policy":self.policy.text(),"width":float(self.width.text()),"height":float(self.height.text()),"resolution":float(self.resolution.text()),"map_noise":float(self.map_noise.text()),"gravity_noise":float(self.gravity_noise.text()),"samples":int(self.samples.text()),"epochs":int(self.epochs.text())}; assert min(v["width"],v["height"],v["resolution"])>0 and v["samples"]>=8
        except Exception: QMessageBox.warning(self,"Settings","Check positive map sizes, resolution, and sample count (>=8)."); return
        self.start.setEnabled(False); self.progress.setValue(0); self.progress.setFormat("Collecting — %p%")
        self.worker=Job(v); self.worker.message.connect(self.append_log); self.worker.progress.connect(self.progress.setValue)
        self.worker.failed.connect(lambda e:(self.append_log(e),self.progress.setFormat("Failed"),self.start.setEnabled(True)))
        self.worker.complete.connect(lambda m:(self.append_log(m),self.progress.setFormat("Complete — 100%"),self.start.setEnabled(True)))
        self.worker.start()
    def current_values(self):
        return {"env":self.env.currentText(),"policy":self.policy.text(),"width":float(self.width.text()),"height":float(self.height.text()),"resolution":float(self.resolution.text()),"map_noise":float(self.map_noise.text()),"gravity_noise":float(self.gravity_noise.text())}
    def show_preview(self):
        if not os.path.isfile(self.policy.text()): QMessageBox.warning(self,"Policy","Select a valid ONNX policy."); return
        try: values=self.current_values(); assert min(values["width"],values["height"],values["resolution"])>0
        except Exception: QMessageBox.warning(self,"Settings","Check map dimensions and noise values."); return
        self.preview=PreviewDialog(self); self.preview.show(); self.preview.activateWindow(); self.preview.setFocus()
        self.preview_worker=PreviewJob(values); self.preview_worker.frame.connect(self.preview.update_maps); self.preview_worker.message.connect(self.append_log); self.preview_worker.failed.connect(lambda error:self.append_log(error)); self.preview.command_changed.connect(self.preview_worker.set_command); self.preview.reset_requested.connect(self.preview_worker.request_reset); self.preview.destroyed.connect(lambda *_: self.preview_worker.stop()); self.preview_worker.start()

if __name__ == "__main__":
    app=QApplication(sys.argv); window=Window(); window.show(); sys.exit(app.exec_())
